### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by scionaltera** [scionaltera/arbitrader#15]
Write unit tests and refactor as necessary.

**Comment by irufus** [comment]
Is there are a target code coverage or this is basically something that people can contribute to if they have time?

**Comment by scionaltera** [comment]
This issue is mostly a reminder so that I will go back and bring the project up to a more reasonable standard of code quality. Maybe it would be better as a 1.0 milestone. If I were reviewing this project at work I'd have more than a few critiques before I allowed it into production.

It's still early and my effort has been focused on just getting it to work at all, but sometime pretty soon it will be time to start breaking apart the `TradingService` "god" class into smaller, more testable components. I didn't want to get bogged down in making it pretty before I could show that it could trade.

I don't have an explicit coverage target in mind, and I'd welcome any tests or refactors that you'd like to contribute. The point isn't to hit a percentage. We want to be confident that the code is doing what we think it should do, and we want to catch regressions quickly. Any tests that cover cases that weren't covered before would be a step forward.

**Comment by scionaltera** [comment]
Not really an actionable ticket.
