### ISSUE TITLE
exchange margin trade support

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#168]
Which exchanges support margin trading except Liquid ?
I can test more like binance,poloniex etc.... just need more information which one works ?

**Comment by sanitariu** [comment]
For example does your bot support margin trading on poloniex and binance ?
I noticed that the bot does not read balance from margin wallet at binance.

**Comment by sanitariu** [comment]
Bot fetches trading fee for poloniex 0.0025 while fees here: https://poloniex.com/fees/
are different.

**Comment by scionaltera** [comment]
Kraken is the other exchange that I use that supports margin trading. Coinbase and Cex.io have just started to offer margin trading but I haven't tried them yet. I'd guess since it's so new XChange won't have support for them yet, so there would be some work to do over there first.

**Comment by sanitariu** [comment]
Hello,
Thanks for the info. Yes i use feeoverride. I can test only liquid,binance,kraken,poloniex,bitstamp,bitfinex with real money. For others i can not register they have some restrictions for EU :(
