### ISSUE TITLE
Exchange fees on the application.yaml

### ISSUE THREAD

**Issue by dazito** [scionaltera/arbitrader#228]
In the configuration yaml file there is the `fees` keyword to specify the exchange fees. What exactly is the fee expected here? I am asking because most (if not all) exchanges have a different fee if you are a maker or a taker in the market.

How should we specify the maker fee and the taker fee? Is it possible?

**Comment by scionaltera** [comment]
Arbitrader will always place a limit order which most exchanges consider a "maker" fee and charge at a lower rate. 

Additionally, Arbitrader will always try to query the exchange's API to retrieve the current fees when it starts up. If it can get the fee directly from the exchange it will override the `fees` value. To confuse the issue a little further, I have found a couple exchanges such as Gemini that have APIs that return the wrong rate for their fees, so there is a `feeOverride` that you can set to make it ignore the exchange's API and force it to use your own value.

The value should be expressed as a decimal. Some examples:

6% would be 0.0006
16% would be 0.0016
60% would be 0.0060

Each exchange configuration has its own `fees` field, so you can define it independently for each exchange.
