### ISSUE TITLE
Simple bookkeeping feature

### ISSUE THREAD

**Issue by dazito** [scionaltera/arbitrader#234]
What do you think of implementing a simple bookkeeping with all entry and exit trades? 
Something pretty much like arbitrader-state.json would be fine. It would make life easier when you have several exchanges.

**Comment by scionaltera** [comment]
Yeah, I think that would be very useful. It would help with some of the work I've been doing around trying to make the bot's prediction of things like fees and profit agree with the actual outcomes. It would also be really nice to have a clearer picture of how you're doing over time.

**Comment by dazito** [comment]
Cool, I will try to implement it over the weekend.
I thought about creating a json file with a json array containing all trades grouped by an UUID. Pretty much like arbitrader-state.json. I think it is already a good starting point. Maybe in the future also export to CSV.
