### ISSUE TITLE
Need a configuration for Binance

### ISSUE THREAD

**Issue by scionaltera** [scionaltera/arbitrader#255]
Binance is a popular exchange that appears to have good support in XChange, and possibly websocket support as well. We should try to get a working configuration for it that can be posted on the Wiki:

https://github.com/scionaltera/arbitrader/wiki/Recommended-Exchange-Configurations

**Comment by sanitariu** [comment]
-
      exchangeClass: org.knowm.xchange.binance.BinanceExchange
      apiKey: x
      secretKey: x
      tradingPairs:
        - BTC/USD
        - ETH/USD
        - XRP/USD
        - ZEC/USD
        - LTC/USD
        - BCH/USD
        - NEO/USD
#        - ADA/USD
        - EOS/USD
      margin: true
      fee: 0.001

      homeCurrency: USDC


This is what i have for binance. ADA pairs gives division by zero error and i can not understand why.
So far bot works with that config but i did not have real traded happen....

**Comment by scionaltera** [comment]
> ```
> -
>   exchangeClass: org.knowm.xchange.binance.BinanceExchange
>   apiKey: x
>   secretKey: x
>   tradingPairs:
>     - BTC/USD
>     - ETH/USD
>     - XRP/USD
>     - ZEC/USD
>     - LTC/USD
>     - BCH/USD
>     - NEO/USD
>     - EOS/USD
>   margin: true
>   fee: 0.001
> 
>   homeCurrency: USDC
> ```
> 
> This is what i have for binance. ADA pairs gives division by zero error and i can not understand why.
> So far bot works with that config but i did not have real traded happen....

Thanks! I'll sign up for an account when I have a chance and see if it works for me too. You can open a separate issue for the divide by 0 problem if you want to.

**Comment by scionaltera** [comment]
Closing this because we have a working configuration for Binance in the docs and are including the Binance library in the main line code now.
