### ISSUE TITLE
Crash on liquid place order

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#262]
arbitrader_1  | 2020-11-14 23:59:59.661  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Summary: [Long/Short Exchanges] [Pair] [Current Spread] -> [Entry Spread Target]
arbitrader_1  | 2020-11-14 23:59:59.798  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Poloniex/Quoine BTC/USD 0.00042921 -> 0.006
arbitrader_1  | 2020-11-14 23:59:59.935  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Bitstamp/Quoine ETH/USD 0.00049860 -> 0.006
arbitrader_1  | 2020-11-15 00:00:00.081  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Bitstamp/Quoine XRP/USD 0.00033515 -> 0.006
arbitrader_1  | 2020-11-15 02:32:21.893  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2020-11-15 02:32:22.302  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.00631413
arbitrader_1  | 2020-11-15 02:32:22.444  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.00718587
arbitrader_1  | 2020-11-15 02:32:22.583  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Bitstamp BCH/USD 0.13812155 @ 253.40 (0.00 slip) = $35.0000007700
arbitrader_1  | 2020-11-15 02:32:22.720  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Quoine BCH/USD 0.13725490 @ 255.00000 (0.00000 slip) = $34.9999995000000
arbitrader_1  | 2020-11-15 02:32:23.621  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Bitstamp $61.13 + Quoine $91.07 = $152.20
arbitrader_1  | 2020-11-15 02:32:24.342 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error executing trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: {"errors":{"order":["product_disabled"]}}
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineBaseService.handleHttpError(QuoineBaseService.java:50)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeServiceRaw.placeLimitOrder(QuoineTradeServiceRaw.java:71)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeService.placeLimitOrder(QuoineTradeService.java:64)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.executeOrderPair(TradingService.java:781)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.entryPosition(TradingService.java:439)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$5(TradingService.java:322)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1259)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:301)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  | Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 422
arbitrader_1  |  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
arbitrader_1  |  at com.sun.proxy.$Proxy49.placeOrder(Unknown Source)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeServiceRaw.placeLimitOrder(QuoineTradeServiceRaw.java:65)
arbitrader_1  |  ... 18 common frames omitted
arbitrader_1  |
arbitrader_1  | 2020-11-15 02:32:24.679  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Polling exchanges took 3176 ms
arbitrader_1  | 2020-11-15 02:32:24.822 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exiting immediately to avoid erroneous trades.
arbitrader_arbitrader_1 exited with code 1

This crashed just before poloniex.
Maybe liquid problem ?
Bitstamp order was executed OK.

**Comment by scionaltera** [comment]
This looks like the important part:

ExchangeException: {"errors":{"order":["product_disabled"]}}

I think it tried to trade a pair that wasn’t allowed on the exchange. Bailing out and avoiding further trades was probably the right thing to do.

**Comment by sanitariu** [comment]
The pair was BCH/USD ... may be something from the fork.
I will not remove the pair for trading. Running again and wait .......

**Comment by sanitariu** [comment]
It happened again. I doubt that i can not trade BCH/USD ... at least it is possible at the web page.
Going to stop that pair.

**Comment by scionaltera** [comment]
“product disabled” sounds to me like the exchange turned that pair off. You’d have to get in touch with them to find out why, and whether it’s temporary or permanent.
