### ISSUE TITLE
Crash on trade

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#263]
Here another crash on trade:

es] [Pair] [Current Spread] -> [Entry Spread Target]
arbitrader_1  | 2020-11-18 05:59:59.895  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Bitstamp/Quoine XRP/USD 0.00
003448 -> 0.006
arbitrader_1  | 2020-11-18 07:47:28.142  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2020-11-18 07:47:28.533  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.00647888
arbitrader_1  | 2020-11-18 07:47:28.669  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.00702
112
arbitrader_1  | 2020-11-18 07:47:28.805  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Quoine XRP/USD 1
20.09745050 @ 0.29143 (0.00000 slip) = $34.9999999992150
arbitrader_1  | 2020-11-18 07:47:28.944  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Poloniex XRP/US
D 119.32436228 @ 0.29331814 (0E-8 slip) = $35.0000000006557592
arbitrader_1  | 2020-11-18 07:47:30.026  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Qu
oine $91.07 + Poloniex $80.31 = $171.38
arbitrader_1  | 2020-11-18 07:47:31.075 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error e
xecuting trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: Not enough XRP.
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adaptBasedOnErrorMessage(PoloniexErrorAdapter.java:31)
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adapt(PoloniexErrorAdapter.java:19)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:115)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.executeOrderPair(TradingService.java:781)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.entryPosition(TradingService.java:439)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$5(TradingService.java:322)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1259)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:301)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  | Caused by: org.knowm.xchange.poloniex.dto.PoloniexException: Not enough XRP.
arbitrader_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
arbitrader_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
arbitrader_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
arbitrader_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
arbitrader_1  |  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call1(AnnotatedConstructor.java:129)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:326)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:147)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
arbitrader_1  |  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
arbitrader_1  |  at com.sun.proxy.$Proxy52.sell(Unknown Source)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.orderEntry(PoloniexTradeServiceRaw.java:150)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.sell(PoloniexTradeServiceRaw.java:115)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:101)
arbitrader_1  |  ... 17 common frames omitted
arbitrader_1  |
arbitrader_1  | 2020-11-18 07:47:31.576  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Polling exchanges took 3908
ms
arbitrader_1  | 2020-11-18 07:47:31.751 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exiting immediately to avoid
 erroneous trades.
arbitrader_arbitrader_1 exited with code 1
Your last login:  dri      pts/9        Tue Nov 17 22:33 - 00:45  (02:11)

Nothing was bought.

**Comment by scionaltera** [comment]
```
ExchangeException: Not enough XRP.
```

Looks like it tried to trade more than your balance. Do you have `fixedExposure` configured? It's possible for that to translate into more than you have available, especially right now when prices are pretty high.

**Comment by sanitariu** [comment]
Yes i have $35:

arbitrader_1  | 2020-11-15 19:31:09.913  INFO 1 --- [           main] c.r.arbitrader.service.TradingService    : Using fixed exposure of $35.
00 as configured
arbitrader_1  | 2020-11-15 19:31:09.913  INFO 1 --- [           main] c.r.arbitrader.service.TradingService    : Using trade timeout of 48 ho
urs
arbitrader_1  | 2020-11-15 19:31:10.563  INFO 1 --- [           main] com.r307.arbitrader.Arbitrader           : Started Arbitrader in 14.733
 seconds (JVM running for 17.13)

**Comment by scionaltera** [comment]
It looks like it failed to execute the short trade on Poloniex because you didn't have enough margin to open the trade. Raising the `fixedExposure` will just make it worse - the trade size will be bigger but your available margin will stay the same. You'll need to add some more funds to Poloniex or close some trades that are open to free up some more margin.

**Comment by sanitariu** [comment]
Ok  I lowered fixedexposure to 30 USD and loaded 146USDC to poloniex.
I hope thats enough.

**Comment by scionaltera** [comment]
> Ok I lowered fixedexposure to 30 USD and loaded 146USDC to poloniex.
> I hope thats enough.

That should be plenty. USDC is 1:1 to USD so I would expect the bot to open a trade for roughly 30 USDC. Having some extra in the account is a good idea to avoid margin calls.
