### ISSUE TITLE
Poloniex crash on trade

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#276]
Hello,
I have another crash at poloniex.
This time other reason:

arbitrader_1  | 2020-11-20 21:14:08.609  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2020-11-20 21:14:08.990  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.00630805
arbitrader_1  | 2020-11-20 21:14:09.127  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.00719195
arbitrader_1  | 2020-11-20 21:14:09.266  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Poloniex XRP/USD 93.99477414 @ 0.31916668 (0E-8 slip) = $29.9999999996136552
arbitrader_1  | 2020-11-20 21:14:09.404  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Quoine XRP/USD 93.40556697 @ 0.32118 (0.00000 slip) = $29.9999999994246
arbitrader_1  | 2020-11-20 21:14:10.536  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Poloniex $146.31 + Quoine $91.05 = $237.36
arbitrader_1  | 2020-11-20 21:14:10.991 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error executing trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: Order matching is currently disabled.
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adaptBasedOnErrorMessage(PoloniexErrorAdapter.java:31)
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adapt(PoloniexErrorAdapter.java:19)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:115)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.executeOrderPair(TradingService.java:780)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.entryPosition(TradingService.java:439)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$5(TradingService.java:322)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1259)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:301)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  | Caused by: org.knowm.xchange.poloniex.dto.PoloniexException: Order matching is currently disabled.
arbitrader_1  |  at sun.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
arbitrader_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
arbitrader_1  |  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call1(AnnotatedConstructor.java:129)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:326)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:147)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
arbitrader_1  |  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
arbitrader_1  |  at com.sun.proxy.$Proxy52.buy(Unknown Source)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.orderEntry(PoloniexTradeServiceRaw.java:160)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.buy(PoloniexTradeServiceRaw.java:111)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:99)
arbitrader_1  |  ... 17 common frames omitted
arbitrader_1  |
arbitrader_1  | 2020-11-20 21:14:11.611  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Polling exchanges took 3485 ms
arbitrader_1  | 2020-11-20 21:14:11.756 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exiting immediately to avoid erroneous trades.
arbitrader_arbitrader_1 exited with code 1

**Comment by scionaltera** [comment]
`org.knowm.xchange.exceptions.ExchangeException: Order matching is currently disabled.`

This means the exchange is not accepting trades right now. Maybe they were closed for maintenance or something.
