### ISSUE TITLE
First time running

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#54]
Anyone knows what could be the reason for the following when i start the bot:
------------------
arbitrader_1  | 2019-03-30 12:02:06.009  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tradingService': Invocation of init method failed; nested exception is org.knowm.xchange.exceptions.ExchangeException: java.net.UnknownHostException: api.kraken.com
arbitrader_1  | 2019-03-30 12:02:06.032 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
arbitrader_1  |
-------------------
I filled correct my kraken keys.

**Comment by scionaltera** [comment]
That means your computer can’t look up api.kraken.com due to a DNS error. That is the same address I am using for Kraken so I think your configuration is probably correct.

Try going to https://api.kraken.com in your browser or with something like curl and see if that works.

**Comment by sanitariu** [comment]
Thank you ! This fixed my problem.

**Comment by sanitariu** [comment]
Hello,
There are new kraken fees.
I think you should update the project.
Thanks for your efforts !

Regards,
Todor

**Comment by sanitariu** [comment]
Hello,
I meant liquid/quone not kraken sorry.

Regards,
Todor

**Comment by scionaltera** [comment]
XChange does not yet support querying Liquid/Quoine for trading fees dynamically so it will fall back to what you have configured in your `application.yaml`. It looks like the correct setting would be `0.001` now instead of `0.002`.

**Comment by scionaltera** [comment]
Updated `application.example.yaml` with the new fee in #55 .

**Comment by sanitariu** [comment]
Hello,
Thank you.
Now i see other crash:

arbitrader_1  | 2019-04-02 07:54:43.826  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2019-04-02 07:54:45.797  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Quoine $66.56 + Kraken $46.16 = $112.72
arbitrader_1  | 2019-04-02 07:54:45.947  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.01119732
arbitrader_1  | 2019-04-02 07:54:46.097  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.00100268
arbitrader_1  | 2019-04-02 07:54:46.244  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Quoine XRP/USD 30.42750647 @ 0.32865 (0.00000 slip) = $10.0000000013655
arbitrader_1  | 2019-04-02 07:54:46.395  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Kraken XRP/USD 30.09057262 @ 0.33234000 (-0.00001000 slip) = $10.0003009045308000
arbitrader_1  | 2019-04-02 07:54:46.912 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: {"message":"Please go to our Trading site (dashboard_url) to review Terms, Conditions and Trading Rules before continuing."}
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineBaseService.handleHttpError(QuoineBaseService.java:51)


Seems like i must confirm something but i can not find anything to confirm.
Also i think that bot is placing long order at liquid.
Do you have more information about this bug ?

If you prefer i can create an issue at your webpage ?

Regards,
Todor

**Comment by sanitariu** [comment]
https://app.liquid.com/update-terms <https://app.liquid.com/update-terms>

This fixed the problem i think.
Sorry for the spam…..

Regards,
Todor

**Comment by sanitariu** [comment]
Hello,
I’ve updated to latest git version.
I had crash.
Attaching screen.log file.




Regards,
Todor Neshev

**Comment by scionaltera** [comment]
> Attaching screen.log file.

I don't see the attachment anywhere?

**Comment by sanitariu** [comment]
[screen.log](https://github.com/scionaltera/arbitrader/files/3055913/screen.log)
Here is the log file. Sorry

**Comment by sanitariu** [comment]
Sorry sending again….

**Comment by scionaltera** [comment]
That is a bug that I'm working on in my current pull request #59 . I am hoping to be able to merge it tonight.
