### ISSUE TITLE
Unable to write state file

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#63]
Crash on Unable to write state file
----------------------------------

arbitrader_1  | 2019-04-09 10:08:39.203  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Slow Tickers! Fetched 17 tickers via getTickers() for Kraken in 4542 ms
arbitrader_1  | 2019-04-09 10:29:51.886  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2019-04-09 10:29:53.420  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Quoine $55.09 + Kraken $43.71 = $98.80
arbitrader_1  | 2019-04-09 10:29:53.556  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.010398
arbitrader_1  | 2019-04-09 10:29:53.690  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.001802
arbitrader_1  | 2019-04-09 10:29:53.826  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Quoine BCH/USD 0.05443223 @ 293.94347 (0.00000 slip) = $15.9999985660381
arbitrader_1  | 2019-04-09 10:29:53.962  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Kraken BCH/USD 0.05387205 @ 297.000000 (0.000000 slip) = $15.99999885000000
arbitrader_1  | 2019-04-09 10:29:54.535 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error executing trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: {"errors":{"order":["product_disabled"]}}
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineBaseService.handleHttpError(QuoineBaseService.java:51)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeServiceRaw.placeLimitOrder(QuoineTradeServiceRaw.java:71)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeService.placeLimitOrder(QuoineTradeService.java:64)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.executeOrderPair(TradingService.java:649)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$null$14(TradingService.java:401)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$null$15(TradingService.java:298)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$16(TradingService.java:290)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:290)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  | Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 422
arbitrader_1  |  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
arbitrader_1  |  at com.sun.proxy.$Proxy47.placeOrder(Unknown Source)
arbitrader_1  |  at org.knowm.xchange.quoine.service.QuoineTradeServiceRaw.placeLimitOrder(QuoineTradeServiceRaw.java:65)
arbitrader_1  |  ... 21 common frames omitted
arbitrader_1  |
arbitrader_1  | 2019-04-09 10:29:54.689 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Unable to write state file!
arbitrader_1  |
arbitrader_1  | java.io.IOException: File 'arbitrader-state.json' exists but is a directory
arbitrader_1  |  at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:352)
arbitrader_1  |  at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:2015)
arbitrader_1  |  at org.apache.commons.io.FileUtils.write(FileUtils.java:2138)
arbitrader_1  |  at org.apache.commons.io.FileUtils.write(FileUtils.java:2107)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$null$14(TradingService.java:413)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$null$15(TradingService.java:298)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$16(TradingService.java:290)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:290)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  |
arbitrader_1  | 2019-04-09 10:29:54.830  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Polling exchanges took 4214 ms
arbitrader_1  | 2019-04-09 10:29:54.965 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exiting immediately to avoid erroneous trades.
arbitrader_arbitrader_1 exited with code 1
dri@dri ~ $

Sorry for creating so much tickets but i am trying to help you make this software better :)

**Comment by sanitariu** [comment]
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: {"errors":{"order":["product_disabled"]}}
May be this is the problem. It happened on BCH trading......
What means product_disabled ?

**Comment by scionaltera** [comment]
I have had to stop trading BCH lately because several of the exchanges I use halt trading on it so frequently. They do that when there are big spikes in the price. Usually it’s just temporary but the bot doesn’t yet do a good job of detecting it. #51 will address that.
