### ISSUE TITLE
Slow tickers warning

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#70]
I think slow tickers warning does not work from config file.
I put there
    slowTickerWarning: 6000

But i see in the logs:

arbitrader_1  | 2019-04-15 06:02:31.367  WARN 1 --- [onPool-worker-7] c.r.arbitrader.service.TradingService    : Slow Tickers! Fetched 9 tickers via getTickers() for Quoine in 3045 ms
arbitrader_1  | 2019-04-15 06:11:51.914  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Slow Tickers! Fetched 16 tickers via getTickers() for Kraken in 5592 ms
arbitrader_1  | 2019-04-15 06:15:11.894  WARN 1 --- [onPool-worker-1] c.r.arbitrader.service.TradingService    : Slow Tickers! Fetched 16 tickers via getTickers() for Kraken in 4572 ms
arbitrader_1  | 2019-04-15 06:28:13.328  WARN 1 --- [onPool-worker-3] c.r.arbitrader.service.TradingService    : Slow Tickers! Fetched empty ticker list for Kraken in 30006 ms

Only last one should be visible ?

**Comment by scionaltera** [comment]
I'll test it again on my end but I'm sure I had it working before I merged it. Make sure the configuration you have is correct because YAML is sensitive to whitespace. It should look like this:

```
notifications:
  logs:
    slowTickerWarning: 6000
```

That's exactly two spaces before "logs" and four spaces before "slowTickerWarning".

**Comment by sanitariu** [comment]
Maybe this is the problem i will do more tests. We can close this.
